# Generated by Django 3.0.7 on 2020-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20201013_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
