# Generated by Django 3.0.7 on 2020-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
