# Generated by Django 2.2 on 2021-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20210226_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
