# Generated by Django 2.2 on 2021-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_notification_sender_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_pic',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
