# Generated by Django 2.2 on 2021-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20210226_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
