# Generated by Django 2.2 on 2021-02-27 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 22, 16, 16, 679675)),
        ),
    ]
