# Generated by Django 2.2 on 2021-02-28 06:46

import datetime
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_notification_mydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_pic',
        ),
        migrations.AlterField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 16, 51, 801230)),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=post.models.user_directory_path),
        ),
    ]
