# Generated by Django 2.2 on 2021-02-28 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20210228_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 12, 37, 57, 441826)),
        ),
    ]
