# Generated by Django 3.1.2 on 2021-06-30 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20210228_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 9, 32, 5, 796508)),
        ),
    ]
