# Generated by Django 3.1.2 on 2021-06-30 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_auto_20210630_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_pic',
        ),
        migrations.AlterField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 9, 52, 54, 723809)),
        ),
    ]
