# Generated by Django 3.1.2 on 2021-06-30 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20210630_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 10, 47, 41, 902632)),
        ),
    ]
