# Generated by Django 2.2 on 2021-02-27 17:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201021_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
